from Tkinter import *
import MySQLdb as m
import random
db=m.connect(host="localhost", user="root", passwd="1234", db="flight")
cur=db.cursor()
'''cur.execute("CREATE TABLE student11(f varchar(45),t varchar(20),name varchar(45),dt int(11), at int(11),seats int(11),price int(11),price1 int(11),fno int(11))")
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("MUMBAI","DELHI","AIRINDIA","20","4","35","12000","9000","1")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("MUMBAI","DELHI","SPICEJET","19","3","35","12000","9000","2")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("MUMBAI","DELHI","INDIGO","5","14","35","12000","9000","3")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("MUMBAI","DELHI","JETAIR","8","17","35","12000","9000","4")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("DELHI","MUMBAI","JETAIR","12","19","35","12000","9000","1")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("DELHI","MUMBAI","INDIGO","20","20","35","12000","9000","2")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("DELHI","MUMBAI","SPICEJET","20","20","35","12000","9000","3")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("DELHI","MUMBAI","AIRINDIA","20","20","35","12000","9000","4")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("MUMBAI","BENGALURU","AIRINDIA","20","4","35","15000","9000","1")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("MUMBAI","BENGALURU","SPICEJET","19","3","35","15000","9000","2")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("MUMBAI","BENGALURU","INDIGO","5","14","35","15000","9000","3")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("MUMBAI","BENGALURU","JETAIR","8","17","35","15000","9000","4")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("BENGALURU","MUMBAI","JETAIR","12","19","35","15000","9000","1")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("BENGALURU","MUMBAI","INDIGO","20","20","35","15000","9000","2")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("BENGALURU","MUMBAI","SPICEJET","20","20","35","15000","9000","3")')
cur.execute('INSERT INTO student11(f,t,name,dt,at,seats,price,price1,fno) VALUES ("BENGALURU","MUMBAI","AIRINDIA","20","20","35","15000","9000","4")')
cur.execute("commit")'''
global str1,str2,current,str3
global str5,str6,str7
class Staff2:
    def Frame7(self):
        root7=Tk()
        root7.title("EDIT FLIGHT DETAILS")
        f7=Frame(root7,height=800,width=1400)
        f7.configure(background="white")
        f7.propagate(0)
        f7.pack()
        l1=Label(text=" From :")
        l2=Label(text=" To   :")
        l3=Label(text=" Flight Name   :")
        l4=Label(text=" Departure Time   :")
        l5=Label(text=" Arrival Time :")
        e1=Entry(f7,width=25,fg='black',bg='white',font=('Arial',14))
        e2=Entry(f7,width=25,fg='black',bg='white',font=('Arial',14))
        e7=Entry(f7,width=25,fg='black',bg='white',font=('Arial',14))
        e4=Entry(f7,width=25,fg='black',bg='white',font=('Arial',14))
        e5=Entry(f7,width=25,fg='black',bg='white',font=('Arial',14))
        l1.place(x=100,y=100)
        e1.place(x=250,y=100)
        l2.place(x=100,y=150)
        e2.place(x=250,y=150)
        l3.place(x=100,y=200)
        e7.place(x=250,y=200)
        l4.place(x=100,y=250)
        e4.place(x=250,y=250)
        l5.place(x=100,y=300)
        e5.place(x=250,y=300)
        def ButtonClick():
            strr1=e1.get()
            strr2=e2.get()
            strr3=e7.get()
            st4=e4.get()
            strr4=int(st4)
            st5=e5.get()
            strr5=int(st5)
            cur.execute("UPDATE student11 set dt=%s WHERE f='%s'AND t='%s'AND name='%s'"%(strr4,strr1,strr2,strr3))
            cur.execute("UPDATE student11 set at=%s WHERE f='%s'AND t='%s'AND name='%s'"%(strr5,strr1, strr2,strr3))
            cur.execute("commit")
            root7.destroy()
        b1=Button(f7,text='SAVE',bg='green',width=5,height=2,command=ButtonClick)
        b1.place(x=300,y=400)
class Staff3:
    def Frame8(self):
        root8=Tk()
        root8.title("EDIT USER DETAIL")
        f8=Frame(root8,height=800,width=1400)
        f8.configure(background="white")
        f8.propagate(0)
        f8.pack()
        l1=Label(text=" Name :")
        l2=Label(text=" Phone   :")
        l3=Label(text=" Booking ID  :")
        e1=Entry(f8,width=25,fg='black',bg='white',font=('Arial',14))
        e2=Entry(f8,width=25,fg='black',bg='white',font=('Arial',14))
        e7=Entry(f8,width=25,fg='black',bg='white',font=('Arial',14))
        l1.place(x=100,y=100)
        e1.place(x=250,y=100)
        l2.place(x=100,y=150)
        e2.place(x=250,y=150)
        l3.place(x=100,y=200)
        e7.place(x=250,y=200)
        def ButtonClick():
            stP1=e1.get()
            stP2=e2.get()
            stP3=e7.get()
            cur.execute("UPDATE student14 set Name='%s' WHERE BookingID='%s'"%(stP1,stP3))
            cur.execute("UPDATE student14 set Phone='%s' WHERE BookingID='%s'"%(stP2,stP3))
            cur.execute("commit")
            root8.destroy()
        b1=Button(f8,text='SAVE',bg='green',width=5,height=2,command=ButtonClick)
        b1.place(x=300,y=400)
class Staff4:
    def Frame9(self):
        root9=Tk()
        root9.title("CANCEL FLIGHT")
        f9=Frame(root9,height=800,width=1400)
        f9.configure(background="white")
        f9.propagate(0)
        f9.pack()
        l1=Label(text=" From :")
        l2=Label(text=" To   :")
        l3=Label(text=" Flight Name   :")
        l4=Label(text=" Booking ID  :")
        e1=Entry(f9,width=25,fg='black',bg='white',font=('Arial',14))
        e2=Entry(f9,width=25,fg='black',bg='white',font=('Arial',14))
        e7=Entry(f9,width=25,fg='black',bg='white',font=('Arial',14))
        e4=Entry(f9,width=25,fg='black',bg='white',font=('Arial',14))
        l1.place(x=100,y=100)
        e1.place(x=250,y=100)
        l2.place(x=100,y=150)
        e2.place(x=250,y=150)
        l3.place(x=100,y=200)
        e7.place(x=250,y=200)
        l4.place(x=100,y=250)
        e4.place(x=250,y=250)
        def ButtonClick():
            stP1=e1.get()
            stP2=e2.get()
            stP3=e7.get()
            stP4=e4.get()
            cur.execute("UPDATE student11 set seats=seats+1 WHERE f='%s'AND t='%s'AND name='%s'"%(stP1, stP2,stP3))
            cur.execute("DELETE FROM student14 WHERE BookingID='%s'"%(stP4))
            cur.execute("commit")
            root9.destroy()
        b1=Button(f9,text='SAVE',bg='green',width=5,height=2,command=ButtonClick)
        b1.place(x=300,y=400)
class Staff1:
    def Frame6(self):
        root6=Tk()
        root6.title("Staff Window")
        f6=Frame(root6,height=800,width=1400)
        f6.configure(background="white")
        f6.propagate(0)
        f6.pack()
        def ButtonClick():
            root6.destroy()
            me=Staff2()
            me.Frame7()

        def ButtonClick1():
            root6.destroy()
            me=Staff3()
            me.Frame8()
        def ButtonClick2():
            root6.destroy()
            me=Staff4()
            me.Frame9()
        f1=PhotoImage(file="flight.gif")
        b1=Button(f6,text="EDIT FLIGHT",width=15,height=5,bg='green',activebackground='yellow',command=ButtonClick)
        b2=Button(f6,text="EDIT USER",width=15,height=5,bg='green',activebackground='yellow',command=ButtonClick1)
        b3=Button(f6,text="CANCEL",width=15,height=5,bg='green',activebackground='yellow',command=ButtonClick2)
        b1.place(x=400,y=300)
        b2.place(x=600,y=300)
        b3.place(x=800,y=300)
class MyOrder:
    global str5,str6,str7,current
    def Frame5(self):
        global str5,str6,str7,current
        root5=Tk()
        root5.title("Booking Window")
        f5=Frame(root5,height=700,width=1400)
        f5.propagate(0)
        f5.configure(background="white")
        f5.pack()
        x=random.randint(10000,11000)
        y=str(x)
        l1=Label(text="From:")
        l2=Label(text="To:")
        l3=Label(text=str1)
        l4=Label(text=str2)
        l5=Label(text="Booking Id:")
        l6=Label(text=y)
        l7=Label(text="Name:")
        l8=Label(text=str5)
        l9=Label(text="Address:")
        l10=Label(text=str6)
        l11=Label(text="Phone no:")
        l12=Label(text=str7)
        l1.place(x=500,y=100)
        l2.place(x=500,y=150)
        l3.place(x=600,y=100)
        l4.place(x=600,y=150)
        l5.place(x=500,y=200)
        l6.place(x=600,y=200)
        l7.place(x=500,y=250)
        l8.place(x=600,y=250)
        l9.place(x=500,y=300)
        l10.place(x=600,y=300)
        l11.place(x=500,y=350)
        l12.place(x=600,y=350)
        cur.execute("UPDATE student14 set BookingID=%s WHERE Name='%s'AND Phone='%s'"%(y,str5,str7))
        cur.execute("commit")
        def ButtonClick():
            global str1,str2,current
            cur.execute("UPDATE student11 set seats=seats-1 WHERE f='%s'AND t='%s'AND fno='%d'"%(str1, str2,current))
            cur.execute("commit")
            root5.destroy()
        def ButtonClick1():
            root5.destroy()
            me2=MyEntry2()
            me2.Frame4()       
        b1=Button(f5,text='SAVE',bg='white',width=5,height=2,activebackground='yellow',command=ButtonClick)
        b2=Button(f5,text='BACK',bg='white',width=5,height=2,activebackground='yellow',command=ButtonClick1)
        b1.place(x=550,y=400)
        b2.place(x=475,y=400)
class MyEntry2:
    global str5,str6,str7
    def Frame4(self):
        global str5,str6,str7
        root4=Tk()
        root4.title("User Window")
        f4=Frame(root4,height=700,width=1400)
        f4.propagate(0)
        f4.configure(background="white")
        f4.pack()
        l1=Label(text="Enter Your name :")
        l2=Label(text="Enter Your Address:")
        l3=Label(text="Enter Your Mobile No :")
        e1=Entry(f4,width=25,fg='black',bg='white',font=('Arial',14))
        e2=Entry(f4,width=25,fg='black',bg='white',font=('Arial',14))
        e3=Entry(f4,width=25,fg='black',bg='white',font=('Arial',14))
        l1.place(x=100,y=100)
        e1.place(x=275,y=100)
        l2.place(x=100,y=150)
        e2.place(x=275,y=150)
        l3.place(x=100,y=200)
        e3.place(x=275,y=200)
        def ButtonClick():
            global str5,str6,str7
            str5=e1.get()
            str6=e2.get()
            str7=e3.get()
            str8='0'
            '''cur.execute("CREATE TABLE student14(Name varchar(45),Address varchar(100),Phone varchar(11),BookingID varchar(11))")
            cur.execute('INSERT INTO student14(Name,Address,Phone,BookingID) VALUES ("%s","%s","%s","%s")'%(str5,str6,str7,str8))
            cur.execute("commit")'''
            root4.destroy()
            me=MyOrder()
            me.Frame5()
        b1=Button(f4,text='SAVE',bg='green',width=5,height=2,activebackground='yellow',command=ButtonClick)
        b1.place(x=300,y=275)
        root4.mainloop()
class MyEntry1:
    global str1,str2,current,str3
    def Frame2(self):
        fnt=("Verdana","13")
        global str1,str2,current,str3
        root2=Tk()
        root2.title("Details WIndow")
        f2=Frame(root2,height=700,width=1400)
        f2.configure(background="white")
        f2.propagate(0)
        f2.pack()
        cur.execute("SELECT * FROM student11 WHERE f='%s'AND t='%s'"%(str1, str2))
        row=cur.fetchall()
        labels=[]
        X=150
        Y=200
        labels.append(Label(text="FROM"+"\t\t"+"TO"+"\t\t"+"FLIGHT"+"\t\t"+"DEP TIME"+"\t\t"+"ARR TIME"+"\t\t"+"PRICE",font=fnt))
        labels[0].place(x=150,y=100)
        def ButtonClick4():
            global current
            current=4
            root2.destroy()
            me2=MyEntry2()
            me2.Frame4()
        def ButtonClick1():
            global current
            current=1
            root2.destroy()
            me2=MyEntry2()
            me2.Frame4()
        def ButtonClick2():
            global current
            current=2
            root2.destroy()
            me2=MyEntry2()
            me2.Frame4()
        def ButtonClick3():
            global current
            current=3
            root2.destroy()
            me2=MyEntry2()
            me2.Frame4()
        if(str3=='Business'):
            for i in range(4):
                labels.append(Label(text=str(row[i][0])+"\t\t"+str(row[i][1])+"\t\t"+str(row[i][2])+"\t\t"+str(row[i][3])+":00"+"\t\t"+str(row[i][4])+":00"+"\t\t"+str(row[i][6]),font=fnt))
                labels[i+1].place(x=X,y=Y)
                Y+=125
        elif(str3=='Economy'):
            for i in range(4):
                labels.append(Label(text=str(row[i][0])+"\t\t"+str(row[i][1])+"\t\t"+str(row[i][2])+"\t\t"+str(row[i][3])+":00"+"\t\t"+str(row[i][4])+":00"+"\t\t"+str(row[i][7]),font=fnt))
                labels[i+1].place(x=X,y=Y)
                Y+=125
        b1=Button(f2,text="BOOK",width=10,height=2,bg='green',fg='yellow',activebackground='yellow',command=ButtonClick1)
        b2=Button(f2,text="BOOK",width=10,height=2,bg='green',fg='yellow',activebackground='yellow',command=ButtonClick2)
        b3=Button(f2,text="BOOK",width=10,height=2,bg='green',fg='yellow',activebackground='yellow',command=ButtonClick3)
        b4=Button(f2,text="BOOK",width=10,height=2,bg='green',fg='yellow',activebackground='yellow',command=ButtonClick4)
        b1.place(x=1200,y=183)
        b2.place(x=1200,y=308)
        b3.place(x=1200,y=433)
        b4.place(x=1200,y=558)
class MyEntry:
    global str1,str2,str3
    def Frame1(self):
        global str1,str2,str3
        root1=Tk()
        root1.title("Entry Window")
        f1=Frame(root1,height=800,width=1400)
        f1.propagate(0)
        f1.configure(background="white")
        f1.pack()
        fnt=("Verdana","13")
        l1=Label(text=" From :",font=fnt)
        l1.place(x=100,y=100)
        l2=Label(text=" To   :",font=fnt)
        l2.place(x=100,y=150)
        e1=Entry(f1,width=25,fg='black',bg='white',font=fnt)
        e1.place(x=200,y=100)
        e2=Entry(f1,width=25,fg='black',bg='white',font=fnt)
        e2.place(x=200,y=150)
        l3=Label(text="Select you Gender:",font=fnt)
        l3.place(x=100,y=200)
        var1=IntVar()
        r1=Radiobutton(f1,variable=var1, value=1, text ='Male',font=fnt)
        r1.place(x=300,y=200)
        r2=Radiobutton(f1,variable=var1, value=2, text ='Female',font=fnt)
        r2.place(x=400,y=200)
        l4=Label(text="Select your option:",font=fnt)
        l4.place(x=100,y=240)
        s=Spinbox(root1,values=("Business","Economy"),font=fnt)
        s.pack()
        s.place(x=290,y=243)
        def ButtonClick():
            global str1,str2,str3
            str1=e1.get()
            str2=e2.get()
            str3=s.get()
            str4=var1.get()
            root1.destroy()
            me=MyEntry1()
            me.Frame2()   
        b4=Button(f1,text="search",width=10,height=2,bg='green',activebackground='yellow',command=ButtonClick)
        b4.place(x=300,y=350)           
class MyButton:
    def WeW(self):
        root =Tk()
        root.title("Welcome Window")
        f=Frame(root,height=800,width=1400)
        f.propagate(0)
        f.configure(background="white")
        f.pack()
        customerPhoto = PhotoImage(file="images1.gif")
        staffPhoto=PhotoImage(file='sta.gif')
        def ButtonClick():
            root.destroy()
            me=MyEntry()
            me.Frame1()
        def ButtonClick1():
            root.destroy()
            me=Staff1()
            me.Frame6()
        b1=Button(f,image=customerPhoto,width=150,height=160,command=ButtonClick)
        b2=Button(f,image=staffPhoto,width=150,height=160,command=ButtonClick1)
        b1.place(x=400,y=230)
        b2.place(x=640,y=230)
        customerLabel = Label(f, text="   CUSTOMER", font=("Poiret One", 15), fg='blue')
        staffLabel = Label(f, text="         STAFF", font=("Poiret One", 15), fg='blue')
        customerLabel.place(x=400, y=400)
        staffLabel.place(x=640, y=400)
        root.mainloop()
mb=MyButton()
mb.WeW()
